params:
  - name: k8sNamespace
    type: string
  - name: imageName
    type: string

modules:
  - name: github.com/qmonus/official-cloud-native-adapters
    revision: v0.20.0

designPatterns:
  - pattern: qmonus.net/adapter/official/kubernetes/deployment/simple
    params:
      k8sNamespace: $(params.k8sNamespace)
      imageName:    $(params.imageName)
      appName: nginx-demo
      port: "80"
      replicas: "1"
  - pattern: qmonus.net/adapter/official/kubernetes/sample:loadbalancer 
    params:
      k8sNamespace: $(params.k8sNamespace)
      appName: nginx-demo
      port: "80"
  - pattern: qmonus.net/adapter/official/pipeline/deploy:simple
  - pattern: qmonus.net/adapter/official/pipeline/sample:resolveIPAddress
