apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: ticekt-1663-verify-staging-deploy
spec:
  params:
    - name: gitRevision
      type: string
  stages:
    - name: build
      spec:
        pipeline: ticekt-1663-verify-nginx-demo-build
        deployment:
          app: ticekt-1663-verify-nginx-demo
          name: ticekt-1663-verify-staging
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: cacheImageName
            value: $(params.imageRegistryPath)/$(params.imageShortName)
    - name: deploy
      spec:
        pipeline: ticekt-1663-verify-nginx-demo-deploy
        deployment:
          app: ticekt-1663-verify-nginx-demo
          name: ticekt-1663-verify-staging
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: imageName
            value: $(stages.build.results.imageFullNameTag)
      runAfter:
        - build
    - name: resolve-ip-address
      spec:
        pipeline: ticekt-1663-verify-nginx-demo-resolve-ip-address-after-deploy
        deployment:
          app: ticekt-1663-verify-nginx-demo
          name: ticekt-1663-verify-staging
      runAfter:
        - deploy
  results:
    - name: ipAddress
      value: $(stages.resolve-ip-address.results.ipAddress)
    - name: imageName
      value: $(stages.build.results.imageFullNameTag)
    - name: gitRevision
      value: $(inputs.gitRevision)