params:
  - name: appName
    type: string
  - name: azureSubscriptionId
    type: string
  - name: azureResourceGroupName
    type: string
  - name: azureDnsZoneName
    type: string
  - name: azureDnsZoneResourceGroupName
    type: string
modules:
  - name: qmonus.net/adapter/official
    revision: v0.23.0
designPatterns:
  - pattern: qmonus.net/adapter/official/adapters/azure/serverless/staticSite/frontend
    params:
      appName: $(params.appName)
      azureDnsZoneName: $(params.azureDnsZoneName)
      azureDnsZoneResourceGroupName: $(params.azureDnsZoneResourceGroupName)
      azureSubscriptionId: $(params.azureSubscriptionId)
      azureResourceGroupName: $(params.azureResourceGroupName)