apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: eso-clustersecretstore-deploy
spec:
  params:
    - name: gitRevision
      description: ""
  results: []
  artifacts: []
  stages:
    - name: eso-deploy
      spec:
        deployment:
          app: external-secrets-operator
          name: staging
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: providerType
            value: kubernetes-helm
          - name: deployStateName
            value: externalsecretsoperator
        pipeline: external-secrets-operator-deploy
    - name: clustersecretstore-deploy
      spec:
        deployment:
          app: external-secrets-operator
          name: staging
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: deployStateName
            value: clustersecretstore
        pipeline: external-secrets-operator-deploy
      runAfter:
        - eso-deploy
