apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: iacs-683-azure-frontend
spec:
  params:
    - name: gitRevision
      description: ""
  results:
    - name: publicUrl
      value: $(stages.publish-site.results.publicUrl)
    - name: gitRevision
      value: $(inputs.gitRevision)
  stages:
    - name: deploy
      spec:
        deployment:
          app: iacs-683-azure-frontend
          name: iacs-863-azure-frontend
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: iacs-683-azure-frontend-deploy
    - name: publish-site
      spec:
        deployment:
          app: iacs-683-azure-frontend
          name: iacs-863-azure-frontend
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: iacs-683-azure-frontend-publish-site
      runAfter:
        - deploy
