apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: iacs-683-gcp-frontend
spec:
  params:
    - name: gitRevision
      description: ""
  results:
    - name: defaultDomain
      value: $(stages.iacs-555-gcp-frontend-publish-site.results.defaultDomain)
    - name: customDomain
      value: $(stages.iacs-555-gcp-frontend-publish-site.results.customDomain)
  stages:
    - name: iacs-555-gcp-frontend-deploy
      spec:
        deployment:
          app: iacs-555-gcp-frontend-deploy
          name: iacs-555-gcp-frontend-deploy
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: iacs-555-gcp-frontend-deploy
    - name: iacs-555-gcp-frontend-publish-site
      spec:
        deployment:
          app: iacs-555-gcp-frontend-deploy
          name: iacs-555-gcp-frontend-deploy
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: iacs-555-gcp-frontend-publish-site
      runAfter:
        - iacs-555-gcp-frontend-deploy
