apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: gcp-frontend-deploy
spec:
  params:
    - name: gitRevision
      description: ""
  stages:
    - name: deploy
      spec:
        deployment:
          app: gcp-frontend-application
          name: gcp-frontend-deployment
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: deploy
    - name: publish-site
      spec:
        deployment:
          app: gcp-frontend-application
          name: gcp-frontend-deployment
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: publish-site
      runAfter:
        - deploy
  artifacts:
    - path: ./
  results:
    - name: defaultDomain
      value: $(stages.iacs-555-gcp-frontend-publish-site.results.defaultDomain)
    - name: customDomain
      value: $(stages.iacs-555-gcp-frontend-publish-site.results.customDomain)
