apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: iacs-555-gcp-frontend-deploy
spec:
  params:
    - name: gitRevision
      description: ""
  stages:
    - name: iacs-555-gcp-frontend-deploy
      spec:
        deployment:
          app: todo-app-frontend
          name: gcp-todo-app-frontend
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: todo-app-frontend-deploy
    - name: iacs-555-gcp-frontend-publish-site
      spec:
        deployment:
          app: todo-app-frontend
          name: gcp-todo-app-frontend
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
        pipeline: todo-app-frontend-publish-site
      runAfter:
        - iacs-555-gcp-frontend-deploy
